### ISSUE TITLE
Scene graph process

### ISSUE THREAD

**Issue by KaiGuo20** [XiaoxinHe/G-Retriever#27]
Hi，
How to solve this ? when I use python -m src.dataset.preprocess.scene_graphs

Traceback (most recent call last):
  File "anaconda3/envs/g_retriever/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "anaconda3/envs/g_retriever/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "workspace/G-Retriever/src/dataset/preprocess/scene_graphs.py", line 121, in <module>
    step_two()
  File "workspace/G-Retriever/src/dataset/preprocess/scene_graphs.py", line 77, in step_two
    _encode_graphs()
  File "workspace/G-Retriever/src/dataset/preprocess/scene_graphs.py", line 66, in _encode_graphs
    edge_attr = text2embedding(model, tokenizer, device, edges.edge_attr.tolist())
  File "/workspace/G-Retriever/src/utils/lm_modeling.py", line 112, in sber_text2embedding
    encoding = tokenizer(text, padding=True, truncation=True, return_tensors='pt')
  File "/anaconda3/envs/g_retriever/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3021, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/anaconda3/envs/g_retriever/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3109, in _call_one
    return self.batch_encode_plus(
  File "/anaconda3/envs/g_retriever/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3311, in batch_encode_plus
    return self._batch_encode_plus(
  File "/anaconda3/envs/g_retriever/lib/python3.9/site-packages/transformers/models/roberta/tokenization_roberta_fast.py", line 225, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/anaconda3/envs/g_retriever/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 562, in _batch_encode_plus
    for key in tokens_and_encodings[0][0].keys():
IndexError: list index out of range

**Comment by XiaoxinHe** [comment]
Hi,

I have fixed it. Please use `git pull` to update the code and rerun the command. Thank you!
