### ISSUE TITLE
Could I run it on Colab?

### ISSUE THREAD

**Issue by giuseppefutia** [XiaoxinHe/G-Retriever#29]
Hi,

Thank you for your work. Do you think is it possible to run it on Colab?

In the paper you mentioned the following:
`Experiments are conducted using 2 NVIDIA A100-80G GPUs.`
Colab Pro is equipped with 1 NVIDIA A100-SXM4-40GB.

I was able to complete the full pre-processing phase, but when I run the following command:
```bash
!CUDA_LAUNCH_BLOCKING=1 python train.py --dataset webqsp --model_name graph_llm
```

I received the following error:
```bash
Building model...
Loading LLAMA
Device 1 is not available, available devices are [0]
Device 1 is not available, available devices are [0]
Loading checkpoint shards:   0% 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/content/G-Retriever/train.py", line 160, in <module>
    main(args)
  File "/content/G-Retriever/train.py", line 52, in main
    model = load_model[args.model_name](graph_type=dataset.graph_type, args=args, init_prompt=dataset.prompt)
  File "/content/G-Retriever/src/model/graph_llm.py", line 43, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4225, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4728, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 993, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 329, in set_module_tensor_to_device
    new_value = value.to(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Do you have any suggestions? And is it possible, in your opinion, to train the model in Colab?

**Comment by XiaoxinHe** [comment]
Hi,
It is possible to run on Colab, but I am not sure if a single A100 GPU with 40GB of memory will work. However, you can try loading the model on a single GPU by modifying the code at the following line:
https://github.com/XiaoxinHe/G-Retriever/blob/504ab567e930a8c55939cdcf65f8d886b18f6a57/src/model/graph_llm.py#L34

to
```
 "max_memory": {0: '40GiB',}, 
```

Thanks!

**Comment by giuseppefutia** [comment]
Thank you for your response! I had already updated this part and successfully ran it on Colab. If you're interested, I also needed to include the following instruction: `model.gradient_checkpointing_enable()` to perform LoRA fine-tuning on Colab. Here's the relevant commit for reference: https://github.com/XiaoxinHe/G-Retriever/commit/2ffca39178a56b904278cd0537e67861a9c49795#diff-f5a2c823a12f792a4a0060ea0c6913595ad3e2a035e58b98223cd9dddb917f59R74.
